'01' => 'atnbd-8-org.stream'
'02' => 'anandatv.stream'
'03' => 'atnislamictv.stream'
'05' => 'atnmusic.stream'
'06' => 'atnws-sg.stream'
'07' => 'banglav000.stream'
'08' => 'bijoy00.stream'
'09' => 'boishakhitv-org.stream'
